services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf

  cpq_db:
    image: postgres:15
    environment:
      POSTGRES_DB: cpq
      POSTGRES_USER: cpq
      POSTGRES_PASSWORD: cpq
    ports:
      - "5433:5432"
    volumes:
      - cpq-db-data:/var/lib/postgresql/data

  cpq_webhook:
    build: ./services/cpq-webhook
    depends_on:
      - cpq_db
    environment:
      DATABASE_URL: postgresql+psycopg2://cpq:cpq@cpq_db:5432/cpq
      ODOO_URL: http://odoo:8069
      ODOO_DB: Lumana_CPQ
      ODOO_USERNAME: kundapurarjun1@gmail.com
      ODOO_PASSWORD: Manuk@539
    ports:
      - "8000:8000"

volumes:
  odoo-web-data:
  odoo-db-data:
  cpq-db-data:
